version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqldock
      MYSQL_USER: test
      MYSQL_PASSWORD: toor
      MYSQL_PORT: 3306
      MYSQL_HOST: db 
    container_name: my-golang-app-db
    command:
      - --default-authentication-plugin=mysql_native_password
  app:
    build:
      context: ./Go
    volumes:
      - .:/go/src/app:rw
    ports:
      - "8088:8088"
    container_name: my-golang-app

